name: Auto-assign labels to PR

on:
  - pull_request

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}